// init/data.js
// Sample PG listings data for seeding the database

const sampleListings = [
  {
    title: "Shree Sai PG for Girls",
    description: "Well-maintained PG for working women and students. Safe locality, warden available 24/7. Home-cooked food included.",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop",
    rent: 7500,
    city: "Pune",
    locality: "Kothrud",
    pgType: "Girls",
    roomType: "Double",
    amenities: ["WiFi", "Food", "Laundry", "AC"],
  },
  {
    title: "Urban Stay Boys PG",
    description: "Modern PG with all amenities. Close to IT parks and metro station. Ideal for IT professionals.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop",
    rent: 9000,
    city: "Pune",
    locality: "Hinjewadi",
    pgType: "Boys",
    roomType: "Single",
    amenities: ["WiFi", "AC", "Gym", "Power Backup"],
  },
  {
    title: "Green Nest Co-ed PG",
    description: "Comfortable co-ed PG with separate floors for boys and girls. Near colleges and shopping malls.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop",
    rent: 8000,
    city: "Mumbai",
    locality: "Andheri West",
    pgType: "Co-ed",
    roomType: "Double",
    amenities: ["WiFi", "Food", "AC", "CCTV"],
  },
  {
    title: "Comfort Zone Girls PG",
    description: "Peaceful girls-only PG in a residential area. All bills included in rent. Near bus stop.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop",
    rent: 6000,
    city: "Nagpur",
    locality: "Dharampeth",
    pgType: "Girls",
    roomType: "Triple",
    amenities: ["WiFi", "Food", "Laundry"],
  },
  {
    title: "Metro Boys Hostel",
    description: "Budget-friendly boys PG near metro. Clean rooms, 24hr security, high-speed internet.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&auto=format&fit=crop",
    rent: 6500,
    city: "Bangalore",
    locality: "Whitefield",
    pgType: "Boys",
    roomType: "Double",
    amenities: ["WiFi", "Power Backup", "CCTV"],
  },
  {
    title: "Sunrise Premium PG",
    description: "Premium single occupancy rooms for working professionals. Fully furnished with attached bathroom.",
    image: "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=800&auto=format&fit=crop",
    rent: 12000,
    city: "Bangalore",
    locality: "Koramangala",
    pgType: "Co-ed",
    roomType: "Single",
    amenities: ["WiFi", "AC", "Food", "Gym", "Laundry"],
  },
  {
    title: "Lotus Girls Hostel",
    description: "Safe and homely girls PG. Walking distance from railway station. Strict no-boys policy.",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&auto=format&fit=crop",
    rent: 5500,
    city: "Hyderabad",
    locality: "Ameerpet",
    pgType: "Girls",
    roomType: "Double",
    amenities: ["WiFi", "Food", "Laundry", "CCTV"],
  },
  {
    title: "Silicon Valley Boys PG",
    description: "Catered towards IT professionals. Flexible food plans, high-speed 100 Mbps WiFi.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop",
    rent: 10000,
    city: "Hyderabad",
    locality: "Gachibowli",
    pgType: "Boys",
    roomType: "Single",
    amenities: ["WiFi", "AC", "Food", "Power Backup"],
  },
  {
    title: "Budget Stay Co-ed PG",
    description: "Affordable co-ed PG for students. Near universities and colleges. Basic amenities covered.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop",
    rent: 4500,
    city: "Pune",
    locality: "Shivajinagar",
    pgType: "Co-ed",
    roomType: "Triple",
    amenities: ["WiFi", "Food"],
  },
  {
    title: "Executive Suites PG",
    description: "Premium PG for senior professionals. Private rooms, attached bathrooms, housekeeping included.",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop",
    rent: 15000,
    city: "Mumbai",
    locality: "Bandra West",
    pgType: "Co-ed",
    roomType: "Single",
    amenities: ["WiFi", "AC", "Food", "Gym", "Laundry", "Power Backup"],
  },
];

module.exports = { data: sampleListings };
